### ISSUE TITLE
./datetimeplugin.cpp:24:10: fatal error: DDBusSender

### ISSUE THREAD

**Issue by Fuhrmann** [CareF/deepin-dock-plugin-datetime#1]
Hey! Trying to build this plugin in my Deepin installation but this error occurs:

```
++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I../../deepin-dock-plugin-datetime -I. -isystem /usr/include/libdtk-2.0.9/DCore -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o datetimeplugin.o ../datetimeplugin.cpp
../datetimeplugin.cpp:24:10: fatal error: DDBusSender: Arquivo ou diretório inexistente
 #include <DDBusSender>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:454: datetimeplugin.o] Error 1
```

I'm missing something?

Thanks.

**Comment by CareF** [comment]
I compiled the project under Arch. DDBusSender is under `/usr/include/libdtk-2.0.9/DCore` (listed in `datetimeplugin.pro`) which may be a different place for other distributions. I believe this header file is part of package `dtkcore`. 

So I think what we can try is: 

1. try install dtkcore if you haven't. 
2. run following command and see where the header file is: 

```
cd /usr/include/
find -name ddbussender.h
```
If it's not `/usr/include/libdtk-2.0.9/DCore` , replace this part in .pro file by what you find.

**Comment by Fuhrmann** [comment]
I've installed dtkcore and updated the .pro file to point to /usr/include/libdtk-2.0.6/DCore/ddbussender.h and it worked now. Thanks!
